# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:10.15
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /var/lib/postgresql/data
    #      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: macheng
      POSTGRES_PASSWORD: macheng
      POSTGRES_DB: macheng
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080